replicaCount: 1

image:
  repository: suryaprasad9773/votingapp
  tag: vote
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: docker-pwd

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources: {}

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: vote.suryadev.shop
      paths:
        - path: /
          pathType: Prefix
  tls: []  # <--- No TLS since you don’t have a TLS secret
