apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    app: {{ include "worker.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "worker.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "worker.name" . }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}{{ if .Values.image.tag }}:{{ .Values.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS
              value: {{ .Values.env.redisHost }}
            - name: DB
              value: {{ .Values.env.dbHost }}
