apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mokadi-suryaprasad/voting-app-helm-charts.git
    targetRevision: HEAD
    path: postgress
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
