apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mokadi-suryaprasad/voting-app-helm-charts.git
    targetRevision: HEAD
    path: .   # since all charts are in the root folders

  destination:
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
