replicaCount: 1

image:
  repository: suryaprasad9773/votingapp
  tag: worker
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  clusterIP: None
  port: 80

imagePullSecrets:
  - name: docker-pwd

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
