replicaCount: 1

image:
  repository: suryaprasad9773/votingapp
  tag: worker
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: docker-pwd

nameOverride: ""
fullnameOverride: ""

env:
  redisHost: redis-redis.development.svc.cluster.local
  dbHost: postgress-db.development.svc.cluster.local
  dbPort: "5432"
  dbUser: postgres
  dbPassword: postgres

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
