replicaCount: 1

image:
  repository: postgres
  tag: "9.4"
  pullPolicy: IfNotPresent

service:
  name: postgres
  type: ClusterIP
  port: 5432

postgresql:
  user: postgres
  password: postgres
  database: postgres
  pgdata: /var/lib/postgresql/data/pgdata

persistence:
  enabled: true
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 1Gi

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
