replicaCount: 1

image:
  repository: redis
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

resources: {}

persistence:
  enabled: false
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
